#pragma once

static const char kHttpRootHtml[] =
    "<!doctype html><html><head>"
    "<meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>leDUO debug</title></head><body>"
    "<style>"
    "body{margin:0;font-family:'Palatino Linotype','Book Antiqua',Palatino,serif;"
    "background:radial-gradient(circle at 10%% 10%%,#1c2b3a 0%%,#0b0f14 60%%);"
    "color:#e9f1ff;}"
    ".wrap{padding:18px;}"
    ".grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;}"
    ".portrait .grid{grid-template-columns:1fr;}"
    ".card{background:rgba(15,25,35,0.75);border:1px solid rgba(120,160,200,0.25);"
    "border-radius:12px;padding:14px;box-shadow:0 10px 30px rgba(0,0,0,0.35);}"
    "h2{margin:6px 0 12px 0;font-weight:600;letter-spacing:0.5px;}"
    ".kv{display:grid;grid-template-columns:130px 1fr;gap:6px;font-size:14px;}"
    "canvas{width:100%%;height:180px;background:#0a1118;border-radius:10px;}"
    ".led-stack{position:relative;width:100%%;aspect-ratio:520/536;}"
    ".led-stack canvas{position:absolute;left:0;top:0;width:100%%;height:100%%;}"
    ".led-overlay{pointer-events:none;}"
    "#overlay{background:transparent;}"
    "#led{background:#ffffff;}"
    ".graph-stack{position:relative;width:100%%;height:180px;}"
    ".graph-stack canvas{position:absolute;left:0;top:0;width:100%%;height:100%%;}"
    ".graph-layer{background:transparent;}"
    "a{color:#9fd6ff;text-decoration:none;}"
    "</style></head><body>"
    "<div class='wrap'>"
    "<h2>leDUO debug</h2>"
    "<div class='grid'>"
    "<div class='card'>"
    "<div class='kv'>"
    "<div>MAC</div><div id='mac'>-</div>"
    "<div>Peer</div><div id='peer'>-</div>"
    "<div>Idle</div><div id='idle'>-</div>"
    "<div>Orientation</div><div id='orientation'>-</div>"
    "<div>Motion</div><div id='motion'>-</div>"
    "<div>Since</div><div id='since'>-</div>"
    "<div>RSSI</div><div id='rssi'>-</div>"
    "<div>Pairing</div><div id='pairing'>-</div>"
    "<div>Local</div><div id='local'>-</div>"
    "<div>Remote</div><div id='remote'>-</div>"
    "</div>"
    "<p><a href='/status'>/status</a> | <a href='/pair/clear'>clear pairing</a></p>"
    "</div>"
    "<div class='card'>"
    "<div>Roll/Pitch</div><canvas id='tilt'></canvas>"
    "<div style='margin-top:10px'>LED Preview</div>"
    "<div class='led-stack'>"
    "<canvas id='led'></canvas>"
    "<canvas id='overlay' class='led-overlay'></canvas>"
    "</div>"
    "<div style='margin-top:10px'>Rolling Graph</div>"
    "<div class='graph-stack'>"
    "<canvas id='graph-base'></canvas>"
    "<canvas id='graph-roll' class='graph-layer'></canvas>"
    "<canvas id='graph-pitch' class='graph-layer'></canvas>"
    "</div>"
    "</div>"
    "</div>"
    "</div>"
    "<script>"
    "const tilt=document.getElementById('tilt');"
    "const graphBase=document.getElementById('graph-base');"
    "const graphRoll=document.getElementById('graph-roll');"
    "const graphPitch=document.getElementById('graph-pitch');"
    "const led=document.getElementById('led');"
    "const overlay=document.getElementById('overlay');"
    "const overlayW=520,overlayH=536;"
    "const ledBox={x:69,y:80,w:390,h:400};"
    "const overlayImg=new Image();"
    "const rollBuf=[],pitchBuf=[];const maxN=120;"
    "function setText(id,v){document.getElementById(id).textContent=v;}"
    "function updateOrientation(){const o=window.innerWidth>window.innerHeight?'landscape':'portrait';"
    "document.body.classList.remove('landscape','portrait');document.body.classList.add(o);"
    "setText('orientation',o);}"
    "function drawTilt(r,p){const ctx=tilt.getContext('2d');"
    "const w=tilt.width=tilt.clientWidth,h=tilt.height=tilt.clientHeight;"
    "ctx.clearRect(0,0,w,h);"
    "ctx.strokeStyle='#2d516b';ctx.lineWidth=2;"
    "ctx.beginPath();ctx.arc(w/2,h/2,Math.min(w,h)*0.35,0,Math.PI*2);ctx.stroke();"
    "const rx=Math.max(-45,Math.min(45,r));"
    "const py=Math.max(-45,Math.min(45,p));"
    "const dx=rx/45* Math.min(w,h)*0.32;"
    "const dy=py/45* Math.min(w,h)*0.32;"
    "ctx.fillStyle='#9fd6ff';ctx.beginPath();ctx.arc(w/2+dx,h/2+dy,8,0,Math.PI*2);ctx.fill();"
    "}"
    "function drawGraph(){const ctxBase=graphBase.getContext('2d');"
    "const w=graphBase.width=graphBase.clientWidth,h=graphBase.height=graphBase.clientHeight;"
    "ctxBase.clearRect(0,0,w,h);"
    "ctxBase.strokeStyle='#1e2a38';ctxBase.lineWidth=1;"
    "for(let i=1;i<4;i++){ctxBase.beginPath();ctxBase.moveTo(0,h*i/4);ctxBase.lineTo(w,h*i/4);ctxBase.stroke();}"
    "const ctxRoll=graphRoll.getContext('2d');const ctxPitch=graphPitch.getContext('2d');"
    "graphRoll.width=w;graphRoll.height=h;graphPitch.width=w;graphPitch.height=h;"
    "ctxRoll.clearRect(0,0,w,h);ctxPitch.clearRect(0,0,w,h);"
    "let maxRoll=5;for(const v of rollBuf){maxRoll=Math.max(maxRoll,Math.abs(v));}"
    "let maxPitch=5;for(const v of pitchBuf){maxPitch=Math.max(maxPitch,Math.abs(v));}"
    "maxRoll=Math.min(maxRoll,90);maxPitch=Math.min(maxPitch,90);"
    "function plot(ctx,arr,color,scale){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();"
    "for(let i=0;i<arr.length;i++){const x=i/(maxN-1)*w;"
    "const y=h/2 - (arr[i]/scale)*(h*0.4);"
    "if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();}"
    "plot(ctxRoll,rollBuf,'#ff9c6b',maxRoll);plot(ctxPitch,pitchBuf,'#7fd1ff',maxPitch);"
    "ctxRoll.font='12px serif';ctxRoll.fillStyle='#ffb493';ctxRoll.fillText('±'+maxRoll.toFixed(0)+'°',8,16);"
    "const rightLabel='±'+maxPitch.toFixed(0)+'°';"
    "ctxPitch.font='12px serif';ctxPitch.fillStyle='#8fd8ff';"
    "ctxPitch.fillText(rightLabel,w-ctxPitch.measureText(rightLabel).width-8,16);"
    "}"
    "function drawOverlay(){"
    "if(!overlayImg.complete)return;"
    "overlay.width=overlayW;overlay.height=overlayH;"
    "const ctx=overlay.getContext('2d');ctx.clearRect(0,0,overlayW,overlayH);"
    "ctx.drawImage(overlayImg,0,0,overlayW,overlayH);"
    "}"
    "function hsv(h,s,v){const c=v*s;const x=c*(1-Math.abs(((h/60)%%2)-1));"
    "const m=v-c;let r=0,g=0,b=0;"
    "if(h<60){r=c;g=x;}else if(h<120){r=x;g=c;}else if(h<180){g=c;b=x;}"
    "else if(h<240){g=x;b=c;}else if(h<300){r=x;b=c;}else{r=c;b=x;}"
    "return [Math.round((r+m)*255),Math.round((g+m)*255),Math.round((b+m)*255)];}"
    "function drawLed(d){const ctx=led.getContext('2d');"
    "const w=led.width=overlayW,h=led.height=overlayH;ctx.clearRect(0,0,w,h);"
    "ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,h);"
    "const cell=ledBox.w/8;"
    "for(let y=0;y<8;y++){for(let x=0;x<8;x++){"
    "ctx.strokeStyle='rgba(80,110,140,0.25)';"
    "ctx.strokeRect(ledBox.x+x*cell,ledBox.y+y*cell,cell,cell);}}"
    "function blob(vx,vy,hue,alpha){const fx=vx/4;const fy=vy/4;"
    "const cx=ledBox.x+(fx+0.5)*cell;const cy=ledBox.y+(fy+0.5)*cell;"
    "const [r,g,b]=hsv((hue||0)/255*360,1,1);"
    "ctx.fillStyle='rgba('+r+','+g+','+b+','+alpha+')';"
    "ctx.beginPath();ctx.arc(cx,cy,cell*0.7,0,Math.PI*2);ctx.fill();"
    "ctx.globalAlpha=alpha*0.5;ctx.beginPath();ctx.arc(cx,cy,cell*1.4,0,Math.PI*2);ctx.fill();"
    "ctx.globalAlpha=1;}"
    "if(d.local_vpos)blob(d.local_vpos[0],d.local_vpos[1],d.local_hue,0.9);"
    "if(d.remote_vpos)blob(d.remote_vpos[0],d.remote_vpos[1],d.remote_hue,0.5);"
    "}"
    "function loadOverlayAssets(){"
    "overlayImg.onload=drawOverlay;"
    "overlayImg.src='/overlay.png';"
    "}"
    "function ingest(d){"
    "setText('mac',d.mac||'-');setText('peer',d.peer||'-');"
    "setText('idle',d.idle?'yes':'no');"
    "updateOrientation();"
    "setText('motion',d.motion?.toFixed(3));"
    "setText('since',d.since_motion_ms+' ms');"
    "setText('rssi',d.rssi+' dBm ('+d.rssi_min+'/'+d.rssi_max+')');"
    "setText('pairing',d.pairing?'open':'closed');"
    "setText('local',d.local_vpos+' hue '+d.local_hue);"
    "setText('remote',d.remote_vpos+' hue '+d.remote_hue);"
    "rollBuf.push(d.roll||0);pitchBuf.push(d.pitch||0);"
    "while(rollBuf.length>maxN){rollBuf.shift();pitchBuf.shift();}"
    "drawTilt(d.roll||0,d.pitch||0);drawLed(d);drawGraph();"
    "}"
    "function poll(){fetch('/status').then(r=>r.json()).then(ingest).catch(()=>{});}"
    "loadOverlayAssets();"
    "setInterval(poll,100);poll();"
    "</script></body></html>";
